### ISSUE TITLE
Redirect to http on accessing the web GUI prevents access behind proxy

### ISSUE THREAD

**Issue by arranpaul** [donaldzou/WGDashboard#161]
Hi,
I wonder if you can help me. I was running v2.3.1 behind a web proxy proxying to the non-SSL http page as SSL with certificates. Unfortunately, on upgrading to v3.0.5 there is an automatic re-direct to http forced by WG Dashboard. For example, if I access the WG Dashboard server IP directly on: http://192.168.0.45:10086 I get the following re-direct http://192.168.0.45:10086/signin?redirect=http://192.168.0.45:10086/ 

Trying to access through an FQDN and SSL via my proxy the proxy will throw a 403 error as the https connection is being re-direct to http and my proxy is set to always connect via https.

Is there a setting or way to prevent this re-direct from occurring? It has only come about in v3.0.5.

Fantastic project btw!

**Comment by donaldzou** [comment]
Hi! I'm sorry that you encountered this problem. If you access the dashboard though the proxy, it will become https? So the URL should be `https://192.168.0.45:10086/signin`

**Comment by arranpaul** [comment]
Hi,

Accessthing through the proxy on an FQDN on https wg dashboard re-directs me to the http version, this is when my proxy will throw a 403 as it is set not to serve http traffic behind a domain for which it has ssl. 

For example if I access WG Dashboard via the proxy on https://wg.mydomain.co.uk I get the following URL presented in my browser: https://wg.mydomain.co.uk/signin?redirect=http://wg.mydomain.co.uk/

Thanks so much!

**Comment by donaldzou** [comment]
Oh I see, so in your case, it should do `redirect=https://...` right?

**Comment by arranpaul** [comment]
That's right but it seems to redirect to http only, there must be a setting to change this, I am just not sure where this would be in your implementation and others might encounter the same issue.

**Comment by donaldzou** [comment]
I thought i hardcoded `http` into the code but found out i didn't. I think is because how your proxy work, so you request https traffic to the proxy server, and behind the proxy server, it was using `http`. So when the dashboard reads the request url, is a http url. I've pushed a fix to the main branch, if you have time, could you please check it out and let me know if it works. You can do the following in `wgdashboard` directory:
```bash
git pull https://github.com/donaldzou/WGDashboard.git && chmod +x src/wgd.sh
```

**Comment by arranpaul** [comment]
Thanks very much for your responses, I can confirm that following the git pull it works! It now loads through the proxy https following the redirect.

You are right, that is how the proxy is configured to work which makes sense why it was re-directing to http only. 

Thanks for fixing, that's brilliant as we can now use through a proxy.

**Comment by donaldzou** [comment]
I'm glad to hear that!! I'm going to do a new release ;)

**Comment by callum-isaac** [comment]
I am still having issues with this update behind a reverse proxy. 

@arranpaul what reverse proxy do you use? & What browser do you use?

I use NGINX Proxy Manager and while using firefox I get the Internal Server Error. This does not happen when using a private browser tab (incognito).

Can you share your setup / configuration?
