### ISSUE TITLE
Private / public keys edited when creating a new peer are not saved

### ISSUE THREAD

**Issue by ilium007** [donaldzou/WGDashboard#375]
**Describe The Problem**
Created a new peer and selected edit slider to add an existing private/ public key combo (migrating existing users) and added existing pre-shared key. The fields went blue to show the keys matched. When saved the peer had a different (generated) private key / public key.

**Expected Error / Traceback**
```
N/A
```

**To Reproduce**
As above

**OS Information:**
 - OS: Debian GNU/Linux 12 (bookworm)
 - Python Version: Python 3.11.2

**Sample of your `.conf` file**
```
N/A
```

**Comment by ilium007** [comment]
Have just tried it again from a fresh install. When I create the new peer and select the edit slider on the keys I enter in a known private / public key pair. I have tried then sliding the edit control closed again (ie. to finish editing) and also just leaving it but the result is the same. When I go back to the front screen the public key has changed away from the one I manually entered.

**Comment by donaldzou** [comment]
Let me look into this.

**Comment by donaldzou** [comment]
Fixed in v4.0.3 :)

**Comment by ilium007** [comment]
Thanks but unfortunately the same thing is happening. I have tried sliding the edit control and adding the private / public keys and clicking +Add as well as closing the Edit control before clicking +Add. Both times it regenerates the keys.

**Comment by donaldzou** [comment]
Ah, once you entered the key manually. There's no need to switch it back

**Comment by ilium007** [comment]
Understood but it still doesn't work for me. I have confirmed I am on latest version and have restarted WGDashboard.

**Comment by ilium007** [comment]
After another restart it seems to be working :) May have been browser cache.
